package service.sharedlib.exceptions.enums;

public enum OrderInvalidReason {
    NONEXISTENT_SERVICE_PROVIDER,
    MENU_ITEM_AND_SERVICE_PROVIDER_DOESNT_MATCH,
    ACCOUNT_IN_INCORRECT_STATUS,
    USER_AND_ACCOUNT_DOES_NOT_MATCH,
    INSUFFICIENT_FUNDS
}
