package service.ordering.domain.enums;

public enum OrderStatus {
    PENDING_SERVICE_PROVIDER_VALIDATION,
    PENDING_MANUAL_SERVICE_PROVIDER_VALIDATION,
    PENDING_ACCOUNT_VALIDATION,
    PENDING_PREPARATION,
    IN_PREPARATION,
    IN_DELIVERY,
    DELIVERED,
    CANCELED
}
